# Generated by Django 2.2.24 on 2021-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleindicatorchart',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='singleindicatorchart',
            name='countries',
        ),
        migrations.AddField(
            model_name='multipleindicatorchart',
            name='image',
            field=models.CharField(max_length=99999, null=True),
        ),
        migrations.AddField(
            model_name='singleindicatorchart',
            name='image',
            field=models.CharField(max_length=99999, null=True),
        ),
    ]
