# Generated by Django 2.2.24 on 2021-06-13 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20210613_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleindicatorchart',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='singleindicatorchart',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
