# Generated by Django 2.2.24 on 2021-06-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ISOS', models.CharField(max_length=30)),
                ('TLD', models.CharField(max_length=30)),
                ('phone_prefix', models.CharField(max_length=30)),
                ('Capital', models.CharField(max_length=30)),
                ('AltNames', models.CharField(max_length=30)),
                ('Region', models.CharField(max_length=30)),
                ('Poblation', models.CharField(max_length=30)),
                ('Coordinates', models.CharField(max_length=30)),
                ('Gentilicio', models.CharField(max_length=30)),
                ('Superficie', models.CharField(max_length=30)),
                ('Gini', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=30)),
                ('borderlines', models.CharField(max_length=30)),
                ('native_language', models.CharField(max_length=30)),
                ('codeX', models.CharField(max_length=30)),
                ('coin', models.CharField(max_length=30)),
                ('oficial_language', models.CharField(max_length=30)),
                ('asociations', models.CharField(max_length=30)),
                ('CIOC', models.CharField(max_length=30)),
                ('flag_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
